version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    volumes:
      - dynamodb_data:/data

  fastfood:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastfood_api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: dynamodb_local
      DB_PORT: 8000
    depends_on:
      - dynamodb-local

volumes:
  dynamodb_data:
    driver: local
