openapi: 3.0.0
info:
  title: API de Usuários
  description: API para gerenciar usuários.
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  # Categoria: Usuários
  /api/users:
    post:
      summary: Cadastrar usuário
      description: Cria um novo usuário no sistema.
      tags:
        - Usuários
      requestBody:
        description: Dados do usuário para criação
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Erro interno do servidor

    get:
      summary: Listar usuários
      description: Retorna todos os usuários não deletados.
      tags:
        - Usuários
      responses:
        '200':
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    email:
                      type: string
        '401':
          description: Token inválido ou não informado
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                  message:
                    type: string
        '500':
          description: Erro interno do servidor

  /api/users/{id}:
    get:
      summary: Buscar usuário pelo id
      description: Retorna os dados de um usuário pelo ID.
      tags:
        - Usuários
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuário encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Erro interno do servidor
    delete:
      summary: Excluir usuário
      description: Realiza a exclusão lógica de um usuário pelo ID.
      tags:
        - Usuários
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Usuário excluído com sucesso (exclusão lógica)
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Erro interno do servidor

  # Categoria: Autenticação
  /api/auth/login:
    post:
      summary: Autenticar usuário
      description: Realiza autenticação local de usuário e retorna um JWT.
      tags:
        - Autenticação
      requestBody:
        description: Credenciais de login
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Autenticado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                  token:
                    type: string
        '400':
          description: Credenciais inválidas
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Erro interno do servidor
  /api/auth/validate:
    post:
      summary: Validar token JWT
      description: Valida o token JWT informado no header Authorization ou no corpo da requisição.
      tags:
        - Autenticação
      security:
        - bearerAuth: []

      responses:
        '200':
          description: Token válido
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                  decoded:
                    type: object
        '401':
          description: Token inválido ou não informado
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                  message:
                    type: string
        '500':
          description: Erro interno do servidor